### ISSUE TITLE
deepak15013

### ISSUE THREAD

**Issue by deepak15013** [IIIT-Delhi/Arche#11]
Add Deepak Sood as a contributor in the static Web Page.

**Comment by deepak15013** [comment]
This is written in the readme - "Make sure you assign the issue to yourself!", but no option was shown to self assign. I think it should be changed.

**Comment by amrandahvur** [comment]
Yeah, Thank you for pointing out :D Correcting it :)

**Comment by amrandahvur** [comment]
Are you sure you wanna close this ? Your PR hasn't been merged yet!

**Comment by deepak15013** [comment]
Sure i was waiting for it. Then i thought it will get merged and closed it. Sorry.
